# Generated by Django 4.1.1 on 2022-10-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_breed',
            new_name='pet_race',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_diet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_feed_amount',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_feed_time_B',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_feed_time_D',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_feed_time_L',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Pet_diet_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_diet', models.IntegerField()),
                ('pet_feed_time_B', models.TimeField()),
                ('pet_feed_time_L', models.TimeField()),
                ('pet_feed_time_D', models.TimeField()),
                ('pet_feed_amount', models.IntegerField()),
                ('pet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Main.pet')),
            ],
        ),
    ]
