# Generated by Django 4.1.1 on 2022-10-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0003_rename_pet_breed_pet_pet_race_remove_pet_pet_diet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_daily_peed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_date', models.DateField(verbose_name='날짜')),
                ('Remain_feed', models.IntegerField(null=True, verbose_name='남은 사료량')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_race',
            field=models.CharField(max_length=100, verbose_name='견종'),
        ),
        migrations.AlterField(
            model_name='pet_diet_set',
            name='pet_diet',
            field=models.IntegerField(verbose_name='식단'),
        ),
        migrations.AlterField(
            model_name='pet_diet_set',
            name='pet_feed_amount',
            field=models.IntegerField(verbose_name='먹이 총량'),
        ),
        migrations.AddField(
            model_name='pet_daily_peed',
            name='pet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Main.pet'),
        ),
    ]
