# Generated by Django 4.1.1 on 2022-10-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Main', '0004_pet_daily_peed_delete_category_alter_pet_pet_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_birth', models.DateField(blank=True, null=True)),
                ('pet_weight', models.DecimalField(decimal_places=5, max_digits=100)),
                ('pet_race', models.CharField(max_length=100, verbose_name='견종')),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='pet_daily_peed',
            name='pet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Main.pet_info'),
        ),
        migrations.AlterField(
            model_name='pet_diet_set',
            name='pet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Main.pet_info'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
