# Generated by Django 4.1.3 on 2022-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0006_pet_daily_feed_delete_pet_daily_peed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_diet_set',
            name='pet_feed_amount',
            field=models.IntegerField(verbose_name='사료 총량'),
        ),
        migrations.AlterField(
            model_name='pet_diet_set',
            name='pet_feed_time_D',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_race',
            field=models.CharField(choices=[('선택', None), ('견종 1', '견종 1'), ('견종 2', '견종 2'), ('견종 3', '견종 3'), ('견종 4', '견종 4'), ('견종 5', '견종 5'), ('견종 6', '견종 6')], max_length=100, verbose_name='견종'),
        ),
        migrations.AlterField(
            model_name='pet_info',
            name='pet_weight',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
