# Generated by Django 4.1.3 on 2022-11-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0007_alter_pet_diet_set_pet_feed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_diet_set',
            name='pet_diet',
            field=models.CharField(max_length=10, verbose_name='식단'),
        ),
    ]
