# Generated by Django 4.1.3 on 2022-11-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0008_alter_pet_diet_set_pet_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_diet_set',
            name='pet_breed',
        ),
        migrations.RemoveField(
            model_name='pet_diet_set',
            name='pet_diet',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_race',
        ),
        migrations.RemoveField(
            model_name='pet_info',
            name='pet_weight',
        ),
        migrations.AddField(
            model_name='pet_diet_set',
            name='pet_feed_Kcal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet_diet_set',
            name='pet_status',
            field=models.CharField(choices=[('중성화', 'Adult_Neutering'), ('미중성화', 'Adult_NonNeutering'), ('비만경향', 'Adult_Obese_NonActive'), ('활동적', 'Adult_Active'), ('매우 활동적', 'Adult_Very_Active'), ('체중감량', 'Adult_Wloss'), ('체중증가', 'Adult_gain'), ('아픔', 'Adult_Week'), ('생후 4개월 전', 'Growth_Ud4'), ('4개월 이후~ 성견 전', 'Growth_Up4'), ('임신 전반 6주', 'Pregent_6W'), ('임신 전반 3주', 'Pregent_3W'), ('수유 1마리', 'Nursing_1'), ('수유 2마리', 'Nursing_2'), ('수유 3~4마리', 'Nursing_3_4'), ('수유 5~6마리', 'Nursing_5_6'), ('수유 7~8마리', 'Nursing_7_8'), ('수유 9마리 이상', 'Nursing_9')], default=1, max_length=100, verbose_name='식단'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet_diet_set',
            name='pet_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet_diet_set',
            name='pet_feed_time_D',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
