# Generated by Django 4.1.3 on 2022-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0010_alter_pet_diet_set_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_diet_set',
            name='pet_needKcal',
            field=models.IntegerField(default=1, verbose_name='하루 필요 칼로리'),
            preserve_default=False,
        ),
    ]
