# Generated by Django 4.1.7 on 2023-12-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0012_alter_pet_diet_set_pet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_daily_feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_date', models.DateField(verbose_name='날짜')),
                ('feed_time', models.TimeField(verbose_name='급여 시간')),
                ('feed_amount', models.IntegerField(verbose_name='급여된 사료량')),
                ('remain_amount', models.IntegerField(null=True, verbose_name='남은 사료량')),
                ('feed_index', models.BooleanField(default=False)),
                ('pet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Main.pet_info')),
            ],
        ),
        migrations.DeleteModel(
            name='Pet_daily_feed',
        ),
    ]
