# Generated by Django 4.1.7 on 2024-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0013_pet_daily_feeding_delete_pet_daily_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_diet_set',
            name='pet_standard_feed',
            field=models.IntegerField(null=True, verbose_name='기준 급식량'),
        ),
    ]
